#!/usr/bin/python
import sys
import re

# Description:
# Take a CSV file generated by Excel with fields in columns
# and transpose column fields to rows. Used these fields to
# then create a basic REDCap instrument to be imported

# PseudoCode/ Steps
# -Add REDCap header
# -Remove trailing or extra spaces from field 
# -Capitalise first letter of each word in Field Name 
# -Transpose columns into rows
# -Convert field names to variable 
# -Add bare minimum field values:
# --> Variable, Form name, Field type and Field Label

# Usage: python scriptname infile.csv "form_name" > outfile.csv

REDCap_header = 'Variable / Field Name,Form Name,Section Header,\
Field Type,Field Label,"Choices,Calculations, OR Slider Labels",\
Field Note,Text Validation Type OR Show Slider Number,Text \
Validation Min,Text Validation Max,Identifier?,Branching Logic \
(Showfield only if...),Required Field?,Custom Alignment,Question \
Number (surveys only),Matrix Group Name,Matrix Ranking?,Field Annotation'

# Print our REDCap instrument header
print REDCap_header
filename = sys.argv[1]
formname = sys.argv[2]

with open(filename) as f:
    for line in f:
        fieldlist = line.split(",")
        for field in fieldlist: 
    #Strip all extra spaces from string
    # Leading and trailing spaces
            field = field.strip()
    
    # Multiple spaces replaced with a single space
            field = re.sub(' +', ' ', field)
    
    #Capitalise all words in field names
            field = field.title()
    
    #Fieldnames to variable names; replace space with underscore
            variablename = field.replace(" ", "_")

            # Print out the bare minimum field values
            #print variablename,',',formname,',,text,',field,",,,,,,,,,,,,,"
            sys.stdout.write("%s,%s,,text,%s,,,,,,,,,,,,,\n" % (variablename, formname, field))
    
